### ISSUE TITLE
Is your test unit test or automation test?

### ISSUE THREAD

**Issue by dumihi313** [nartc/ng-conduit#3]
I saw you handle a lot of stuff in the .spec file, I don't know if your test case is a unit test or an integration test ? 
Because I saw your test is described results interacting with UI like"

 describe('When edit form', () => {
    describe('Given invalid form', 
...

**Comment by nartc** [comment]
You're right. Most components/directives' tests can be considered integration tests as it tests against the rendered DOM. Store/Services are Unit Tests.
